// SPDX-License-Identifier: MIT
// esbuild build script for the kwinscript subproject.
//
// Bundles src/index.ts into dist/kwinscript.js — a single IIFE file that KWin
// loads through org.kde.kwin.Scripting.loadScript. The bundle must not depend
// on Node.js or browser globals: it runs inside KWin's QJSEngine.
//
//   node esbuild.build.mjs          # one-shot build
//   node esbuild.build.mjs --watch  # rebuild on changes

import * as esbuild from "esbuild";
import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";

const watch = process.argv.includes("--watch");

const options = {
    entryPoints: ["src/index.ts"],
    bundle: true,
    format: "iife", // plain script, no module wrapper — what KWin expects
    platform: "neutral",
    target: ["es2020"],
    outfile: "dist/kwinscript.js",
    legalComments: "none",
    banner: {
        js: "// kwin-api-server kwinscript bundle (generated by esbuild) — do not edit.\n" +
            "// Source: kwinscript/src/index.ts",
    },
    logLevel: "info",
};

await mkdir(dirname(options.outfile), { recursive: true });

if (watch) {
    const ctx = await esbuild.context(options);
    await ctx.watch();
    console.log("watching kwinscript/src for changes ...");
} else {
    await esbuild.build(options);
}
